name: After merging PR

on:
  push:
    branches:
      - master
      - main
      - build_test

jobs:
  devel-tag-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install dependencies PyYAML
      run: |
          python -m pip install --upgrade pip
          pip install PyYAML
    - name: Generate
      run: "rev=$(git rev-parse --short HEAD) ./generate.sh"
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./src
        enable_jekyll: true
